// <auto-generated/>
namespace Bootstrap
{
    using Honeywell.GuidedWork.Core;

    ///<summary>
    /// Override the string properties in this class to present build
    /// information that identifies your product in logs, problem
    /// reports, and the "About Application" Settings screen.
    ///</summary>
    public class AppBuildInfo : IAppBuildInfo {
        public static void Register(TinyIoC.TinyIoCContainer container) {
            container.Register<IAppBuildInfo, AppBuildInfo>();
        }

        /// <summary>
        /// Build timestamp (in format YYYY-MM-DD HH:MM).
        /// </summary>
        public string BuildDate => "";

        /// <summary>
        /// Build configuration (e.g. Debug, Release).
        /// </summary>
        public string BuildConfiguration => "";

        /// <summary>
        /// Git branch and commit.
        /// </summary>
        public string BuildBranch => "";

        /// <summary>
        /// User who built the app and hostname of machine used (in format User@Hostname).
        /// </summary>
        public string BuildUser => "";
    }
}
