//////////////////////////////////////////////////////////////////////////////
//    Copyright (C) 2017 Honeywell International Inc. All rights reserved.
//////////////////////////////////////////////////////////////////////////////

namespace WarehousePicking
{
    using GuidedWork;
    using System.Resources;

    /// <summary>
    /// A class built from a pared-down auto-generated designer file for gaining
    /// access to the resources from WarehousePickingResources.resx.  Since we aren't
    /// actually referencing any of the symbols generated by the designer, save
    /// some code and reduce the size of the app.
    /// </summary>
    public static class WarehousePickingResources
    {
        private static ResourceManager _ResourceManager;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_ResourceManager, null))
                {
                    _ResourceManager = EmbeddedResourceUtil.GetResourceByType(typeof(WarehousePickingResources));
                }
                return _ResourceManager;
            }
        }
    }
}
